### ISSUE TITLE
Config object documentation is misleading

### ISSUE THREAD

**Issue by fresheneesz** [EventEmitter2/EventEmitter2#137]
In the following config object, one would expect that the values there are the defaults. Except for the fact that defaults are specified for the last two, I would think nothing is amiss and would simply misunderstand your docs. This should be documentation, not an example. I recommend changing the values to their defaults. Example values are just confusing here. Remember documentation is no the same thing as examples.

```
  var EventEmitter2 = require('eventemitter2').EventEmitter2;
    var server = new EventEmitter2({

      //
      // use wildcards.
      //
      wildcard: true,

      //
      // the delimiter used to segment namespaces, defaults to `.`.
      //
      delimiter: '::', 

      //
      // if you want to emit the newListener event set to true.
      //
      newListener: false, 

      //
      // max listeners that can be assigned to an event, default 10.
      //
      maxListeners: 20
    });
```

**Comment by fresheneesz** [comment]
Proof that its misleading: https://github.com/asyncly/EventEmitter2/issues/130

**Comment by jnwelzel** [comment]
Are these the only options available? What are their defaults? I would be willing to create a PR for this.

**Comment by RangerMauve** [comment]
@jnwelzel 
- `wildcard` is undefined, by the looks of it
- `delimiter` is "-" [defined here](https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L227)
- `newListener` is `false` [defined here](https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L40)
- `maxListeners` is `10` [defined here](https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L13)

**Comment by jnwelzel** [comment]
@RangerMauve thank you, I'll get to it then.

**Comment by RangerMauve** [comment]
Feel free to modify the source to have a default config object in there. :D
