### ISSUE TITLE
ReferenceError: window is not defined when using Workers

### ISSUE THREAD

**Issue by Darker** [EventEmitter2/EventEmitter2#153]
If I do this in web worker:

```
importScripts("http://127.0.0.1/lines/eventemitter2.js");
```

I get an error as in title. I thought this library was supposed to be compatible with node.js. So why use window? Actually, why does it execute anything on `window` when just being loaded? Shouldn't such calls be lazy?

**Comment by RangerMauve** [comment]
It's doing that because of the AMD wrapper so that it'd work with various dependency managers without any issues. Try using it with browserify as a quick fix

**Comment by Darker** [comment]
I fixed it like this:

        var window = {};
        importScripts("eventemitter2.js");
        self.EventEmitter2 = window.EventEmitter2;

You could use `self` for best compatibility, it allways reffers to global scope unless overriden. And in case of workers, I don't think there's other global scope refference than `self` and `this` (which is overriden in class methods).

**Comment by RangerMauve** [comment]
A PR would be very much appreciated for this.
