### ISSUE TITLE
Is emitting on a symbol channel supported?

### ISSUE THREAD

**Issue by bcherny** [EventEmitter2/EventEmitter2#201]
```js
const emitter = new EventEmitter2
const CHANNEL = Symbol('MyChannel')
emitter.emit(CHANNEL, 'foo')
```

**Comment by RangerMauve** [comment]
This hasn't actually been tested before. My gut feeling is that it won't work nicely if you have wildcards enabled since the event string gets split up by separators and turned into a tree (which won't work with Symbol as it's not a string type).

**Comment by bcherny** [comment]
That's what I figured too. Would you be interested in a PR to support Symbols, or is it beyond the scope of this lib?

**Comment by RangerMauve** [comment]
If it didn't hurt performance, I could see it being a useful addition. Though I don't know if it'd really be worth bringing everything else in if all you want is an event emitter that uses symbols.

**Comment by bcherny** [comment]
I wonder if you could model nested/wildcard channels with Symbols too:

```js
import { EventEmitter2, Any } from 'eventemitter2'

const A = Symbol('A')
const B = Symbol('B')

const emitter = new EventEmitter2
emitter.on(A, () => {})
emitter.on([A, B], () => {})
emitter.on([A, Any], () => {})
```

**Comment by RangerMauve** [comment]
Yeah, at that point I'd probably suggest making a separate symbol-based version. It should be easy enough to create a tree using an array of symbols and use that for looking up listeners.
