### ISSUE TITLE
eventNames function does not work with wildcard events

### ISSUE THREAD

**Issue by more7dev** [EventEmitter2/EventEmitter2#214]
Hello!
The recently added function 'eventNames' only works with 'wildcard' option disabled. If this is intentional it should be at least noted in the README. 
I believe it's a bigger issue for all function that base on the 'EventEmitter2._events' being populated. In case of wildcard event a tree is used instead of a flat register. This seems not to be supported by some utility functions (listeners, etc.). The unit tests should also cover this scenario.
Core functionality (emitting, listening) works fine.

**Comment by PascalPflaum** [comment]
The "newListener" Event isn't fired as well, if wildcards are enabled.

**Comment by RangerMauve** [comment]
Sadly I haven't had much time to spend on this repo since I'm not actively using it any more. Contributions from the community would be super welcome.
