### ISSUE TITLE
Changelog for v5.0.0?

### ISSUE THREAD

**Issue by icebob** [EventEmitter2/EventEmitter2#226]
Hi,

you have released a new major version v5.0.0 on NPM, but I don't find any information in changelog or releases. What are the breaking changes?

Thanks!

**Comment by RangerMauve** [comment]
Sorry about that, the changes are in #207 

`removeListener` option has changed.

**Comment by icebob** [comment]
What are the breaking changes in the version 6.0.0? Thanks in advance.

**Comment by RangerMauve** [comment]
It's in the latest release notes: https://github.com/EventEmitter2/EventEmitter2/releases

It shouldn't affect you if you're not using the `_events` property in the event emitter in your code, but I wanted to err on the safe side and not break anybody's builds.
