### ISSUE TITLE
Move to github org

### ISSUE THREAD

**Issue by 0x00A** [EventEmitter2/EventEmitter2#233]
This is a community project, it should have its own org. Unless anyone has any reasonable objections, I'd like to move it to `https://github.com/EventEmitter2/EventEmitter2`.

cc @RangerMauve

**Comment by RangerMauve** [comment]
I'm all for it! :D

**Comment by RangerMauve** [comment]
Could I get a higher level of access to add potential collaborators when they come up?

**Comment by 0x00A** [comment]
@RangerMauve of course! Ok, then I will move it.
