### ISSUE TITLE
listeners method incorrectly identifies wrong listener

### ISSUE THREAD

**Issue by ScottChapman** [EventEmitter2/EventEmitter2#234]
So, I am using wildcards, and '-' as delimiter.

I have one (and only one) listener like:
```
Express.on('**-focus-**', event => {
  console.log("Got focus!");
  console.log(JSON.stringify(event,null,2));
})
```

But, when I get the list of listeners like:
`if (emitter.listeners("completed-**").length > 0) {`

The listener above is returned in the array.

**Comment by RangerMauve** [comment]
Not sure why that's happening. :P

Sadly I don't have time to work on it at the moment, but a PR with a test case would be very appreciated!

**Comment by ScottChapman** [comment]
OK, I think I got it.
the listener is on `**-focus-**` which means the events *could* start with anything, including `completed-**`
