### ISSUE TITLE
Error: https://registry.npmjs.org/EventEmitter2: Not found

### ISSUE THREAD

**Issue by RichAyotte** [EventEmitter2/EventEmitter2#241]
It was working a few hours ago but the package now seems to be missing from the registry.

https://registry.npmjs.org/EventEmitter2

currently returning:
```json
{"error":"Not found"}
```
Maybe NPM is case sensitive now because the following works.

https://registry.npmjs.org/eventemitter2

However, it doesn't help package managers.
```shell
$ yarn add eventemitter2
yarn add v1.13.0
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/EventEmitter2: Not found".
```

**Comment by RangerMauve** [comment]
I'm not sure why yarn would be capitalizing EventEmitter2 since it's lowercase in the package.json and everywhere else.

**Comment by RichAyotte** [comment]
Must have been a blip because it's working now.
