### ISSUE TITLE
vulnerabilities

### ISSUE THREAD

**Issue by brianHolonis** [EventEmitter2/EventEmitter2#242]
I cloned the repo and installed it and saw the message listed at the bottom of this message. Is it a bad idea to use this EventEmitter2 now? Do you have any modules you suggest to use instead? 

message seen after installing EventEmitter2 with npm install
__________________________________________________________________________________
found 10 vulnerabilities (9 moderate, 1 high) run `npm audit fix` to fix them, or `npm audit` for details

$ npm audit

                 === npm audit security report ===   
                     
# Run  npm install --save-dev nyc@14.1.1  to resolve 10 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change

**Comment by RangerMauve** [comment]
Nyc is a dev dependency so it's not actually being loaded if you're installing EventEmitter2 as a dependency.

A PR to update the version in package.json would also be welcome. 😁

**Comment by bmhardy** [comment]
I installed it and all was well. Thanks.
