### ISSUE TITLE
Fix build badge & coverage scripts 

### ISSUE THREAD

**Issue by DigitalBrainJS** [EventEmitter2/EventEmitter2#249]
We should fix the badge in Readme with build status, because "build failed" can be confusing for users.
It seems the coverage script is broken too. So it would be nice to fix this and make integration with Travis-ci.
- [x] Create `release/dev` branch
- [x] Setup Travis service
- [x] Setup Coveralls service

**Comment by DigitalBrainJS** [comment]
Is there any progress with CI setup on Travis & Coveralls? Travis config and scripts already merged into the master, so it remains only to activate watching for the repo inside these services. 
@RangerMauve , you're our only hope to solve this issue, having write permissions ;)

**Comment by DigitalBrainJS** [comment]
@RangerMauve Would you mind giving me write access to the repository or suggest someone who could consider my request?
It would be nice if I had direct access to the release / dev branch and I could integrate this repo with my profile on Travis & coveralls.io to get working CI testing & relevant build status indicated by the repo badges. At least, this may simplify my workflow and your future reviews and/or merging branches for releases.

**Comment by RangerMauve** [comment]
@DigitalBrainJS Yeah! Sorry for the radio silence. I've been hella sick the past few weeks and then hella busy catching up with contracts.

I think that would work out. I'll see if I can add you to the collaborator list. 💜 Only request is that we discuss breaking changes before merging them in if possible.

**Comment by RangerMauve** [comment]
Added you in! Feel free to merge any of the outstanding PRs if the tests are passing. 😁

**Comment by DigitalBrainJS** [comment]
Wow, thanks a lot!💚
Of course we will discuss each release (merging dev to the master), even non breaking, since in any case the npm repo is under your control :)
I aim to avoid any breaking changes and there seems to be no reason for this, so the only potential breaking changes could be here is bug fixes like #254 :)
So, currently my goal is:
- keep the API signature
- keep the core methods constuctor/on/off/emit as fast as posible
- bring new features that may be usefull for folks. 
- bug fixes and a bit of performance optimizations (the current banchmark test measurens only basic usage)

I will notify you when the `dev` branch will be ready for review and release, of course, if you will have some time and inspiration for this :)

**Comment by DigitalBrainJS** [comment]
Hmm, are you sure you added me? 😉 
I still see the label `Only those with write access to this repository can merge pull requests.` and it's still missing in my travis repo list :)
I just tried to push an empty `dev` branch and i got the following:

`Remote: Permission to EventEmitter2/EventEmitter2.git denied to DigitalBrainJS. unable to access 'https://github.com/EventEmitter2/EventEmitter2.git/': The requested URL returned error: 403`

**Comment by RangerMauve** [comment]
It says the invite is pending so you might need to check your email to accept it. :P

**Comment by DigitalBrainJS** [comment]
Oops, you're right :) I don’t know why, but github sent my invite to the secondary email, while all notifications always come to the primary email address...

**Comment by DigitalBrainJS** [comment]
@RangerMauve Oh, unfortunately, this still does not let me to import the original repo into my Travis-ci account. I'm not sure about the github access levels that Travis needs (https://github.com/travis-ci/travis-ci/issues/2519#issuecomment-97322783), most likely I need to be a member of the organization for this, so it seems that Travis integration is still a challenge just for you :) It would be nice if you could log in using your github account on Travis (https://travis-ci.com/account/repositories) and turn on the flag for this repo 🙂

**Comment by RangerMauve** [comment]
Looks like I needed to request access to Travis for this org, but I think @heapwolf could probably grant that once he has time. 😅

**Comment by DigitalBrainJS** [comment]
It's a pity) Let's hope for the best) 
BTW it strange because it seems earlier this repo already had an integration with Travis (https://github.com/EventEmitter2/EventEmitter2/commit/0dd0bce457b22270536496f600c780e63f3802fe#diff-354f30a63fb0907d4ad57269548329e3), but it was delated in https://github.com/EventEmitter2/EventEmitter2/commit/4b5d926396323fddb09a026df1a97794081d739f#diff-354f30a63fb0907d4ad57269548329e3 😮

**Comment by RangerMauve** [comment]
@DigitalBrainJS Should be good to go now!

**Comment by DigitalBrainJS** [comment]
@RangerMauve Hmm. Nothing seems to have changed. At least i can't see this repo in my available repo list...

**Comment by RangerMauve** [comment]
How about now? I granted access to travis and travis open source. Maybe you need to sync your github account with it again?

**Comment by DigitalBrainJS** [comment]
unfortunately, there are no progress :(
I sync my travis account, but i can see only my fork, without origin repo. I think that's becasuse i have only push access, and as i know travis doesn't show such repo in its list, only if user is a memer of an org. So it's just turn on integration from your account... and add env variable for coveralls.

**Comment by DigitalBrainJS** [comment]
@RangerMauve  can you to see this repo in the repo list of your Travis account? :)

**Comment by RangerMauve** [comment]
Github says I've given the organization access, https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac

On travis I'm not seeing EventEmitter2 and it's just stuck saying it's syncing with github

**Comment by DigitalBrainJS** [comment]
@RangerMauve BTW are you tried travis-ci.com or travis-ci.org?

**Comment by RangerMauve** [comment]
I was using.com, but I also granted whatever version you had sent a request for. :O

**Comment by RangerMauve** [comment]
Oh neat, I see it in my list when I use `.org`

**Comment by DigitalBrainJS** [comment]
Holly Gods of JavaScript! 😃 Yeap, it's an older version of the service. Can it be activated?
P.S. I can't see it in any version...

**Comment by RangerMauve** [comment]
![image](https://user-images.githubusercontent.com/911495/81238037-05692300-8fcf-11ea-85f7-8c9f2d687914.png)

It looks like it already is? 😅

**Comment by DigitalBrainJS** [comment]
Yeah) Finally) Now we need to do the last step- integrate it with coveralls.io
- login on coveralls
- import the repo,
- copy the TOKEN 
- login on travis and go to the repo settings
- paste token as an environment variable COVERALLS_REPO_TOKEN 
- done 👍

**Comment by DigitalBrainJS** [comment]
I fixed th badge link to *.org and make some changes to the README. So when we'll be sure that coveralls badge is working fine we need to make a patch version for npm.

**Comment by RangerMauve** [comment]
@DigitalBrainJS For some reason the EventEmitter2 org isn't showing up in the list of repos. 😅

**Comment by DigitalBrainJS** [comment]
@RangerMauve Oh, you have broken my hopes :D Did you sync repo list?

**Comment by DigitalBrainJS** [comment]
@RangerMauve what about https://coveralls.io/refresh?private=true ?

**Comment by DigitalBrainJS** [comment]
@RangerMauve I have requested access for the service :)
![image](https://user-images.githubusercontent.com/12586868/82491192-00d35d00-9aed-11ea-931c-8c38b11c7bab.png)

**Comment by RangerMauve** [comment]
Thanks! I approved the request, is it working now?

**Comment by DigitalBrainJS** [comment]
@RangerMauve Not really. It still requires your coveralls.io repo token as an environment variable for Travis build (COVERALLS_REPO_TOKEN). If you can see now this repo in your coveralls.io account you need get a token there for using it with Travis.

**Comment by RangerMauve** [comment]
I'm still not seeing it in the coveralls.io list. 😩

**Comment by DigitalBrainJS** [comment]
@RangerMauve Hmm. Then I have to use Google again: D

**Comment by RangerMauve** [comment]
I see coveralls in the Third Party Access section on the org, but when I open coveralls I don't see the repo listed anywhere. 🤷

**Comment by DigitalBrainJS** [comment]
@RangerMauve Did you tried to click "Repo Sync" in the Pro Sign Up on the left menu?

**Comment by RangerMauve** [comment]
Yeah, I've tried that a bunch of times now. 🤷 It shows every org I'm in except EventEmitter2 😂

**Comment by RangerMauve** [comment]
Wow, I just did it again and it started showing up. 🤷 What the heck even.

**Comment by DigitalBrainJS** [comment]
This is definitely some kind of voodoo spell 😄

**Comment by RangerMauve** [comment]
K, copied thetoken into travis under COVERALLS_REPO_TOKEN 😁

**Comment by DigitalBrainJS** [comment]
Cool. That works now 👍 Rebuilded. But the bage is still "unknow" :) Maybe a wrong link for the bage, checking...
