### ISSUE TITLE
Consider adding responds(type) method

### ISSUE THREAD

**Issue by lehni** [EventEmitter2/EventEmitter2#251]
Would you consider adding such a method that allows to check if the emitter responds to a given event?

```js
EventEmitter.prototype.responds = function(type) {
  return !!(this._all || this._events && this._events[type]);
};
```

I'm happy to create a PR if this is of use.

**Comment by RangerMauve** [comment]
I think this could also be done with [`emitter.listeners](type).length`](https://github.com/EventEmitter2/EventEmitter2#emitterlistenerseventname) right?

Is that hard enough to use that a new method should be made? Or is it maybe a performance thing?

**Comment by DigitalBrainJS** [comment]
There is a bug:
```
const EE= require('../index').EventEmitter2;
const ee= new EE();
const handler= function(){};
ee.onAny(handler);
ee.offAny(handler);
console.log(ee.responds('event')); //true
```
The `_all` property [can be set](https://github.com/EventEmitter2/EventEmitter2/blob/191e0ff0ea09e3c87aac2adae2a07e83a456ca5e/lib/eventemitter2.js#L868) only to [], not to null, so it’s forever true after initialization.
In addition, currently the implementation does not take into account wildcard handlers.

P.S. I was going to refactor the internal implementation of 'all' handlers, because it seems we don't need to have the separate array for this. We could just use the _events[EMPTY_STRING] or _events[Symbol()] to store the 'all' handlers. Then we could make an option in
`listenerCount(event, {all: true|false})` to determine if an event has listeners at all.

**Comment by lehni** [comment]
@RangerMauve I think it would be a nice addition, as it would be semantically quite readable:
```js
if (emitter.responds('event-type')) {
  // Do some heavy processing that is only required when somebody is actually listening
  // to the event emitted, then emit:
  emitter.emit('event-type', data);
}
```

@DigitalBrainJS thanks for pointing that out. It would be easy to address that without changing the rest of the code:

```js
EventEmitter.prototype.responds = function(type) {
  return !!(this._all && this._all.length > 0 || this._events && this._events[type]);
};
```

**Comment by lehni** [comment]
With ES2020, it could be simplified to:

```js
EventEmitter.prototype.responds = function(type) {
  return !!(this._all?.length > 0 || this._events?.[type]);
};
```

**Comment by DigitalBrainJS** [comment]
Hm, I'm not a native English speaker, but would the name 'emitter.isListening([event])' be more clear?
I believe that it would be better if the event parameter will be optional to expand use cases.
We are still with ES5 here to keep the widest compatibility :)

**Comment by lehni** [comment]
I think it would have to be `isListeningTo(event)` then. But how about`hasListeners([type])`? That would work both with and without the `type` argument.

**Comment by DigitalBrainJS** [comment]
> hasListeners([type])
Even better.
This seems to be useful for performance reasons. But we need to implement EE support in wildcard mode, so we need to add a temporary implementation with some performance overhead for a while using the internal searchListenerTree function:
```
  if (this.wildcard) {
      handlers = [];
      var ns = typeof type === 'string' ? type.split(this.delimiter) : type.slice();
      searchListenerTree.call(this, handlers, ns, this.listenerTree, 0);
      return handlers.length > 0;
  }
```
P.S. I believe you should make the PR, as it looks like @RangerMauve is very responsive and open to new contributions :)

**Comment by lehni** [comment]
Thanks @DigitalBrainJS for taking care of this!
