### ISSUE TITLE
waitFor does not clear listener once resolved

### ISSUE THREAD

**Issue by kelvinhammond** [EventEmitter2/EventEmitter2#262]
Thank you for this excellent library.
There is a bug, I think the library is still good.
It does not clear the listener when `waitFor` has been resolved. 
Here is an example.
```
const EventEmitter2 = require('eventemitter2');
const emitter = new EventEmitter2();

console.log(emitter.listeners())
# > []

const promise = emitter.waitFor('event').then(() => { console.log('here'); });
console.log(emitter.listeners());
# > [ [Function: listener] ]

emitter.emit('event');
# > here

console.log(emitter.listeners());
# > [ [Function: listener] ]
```
At the end it should be `# > []` but there still remains on listener bound which later causes...
> MaxListenersExceededWarning: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

A good solution / workaround that I use:
```
return new Promise((resolve, reject) => {
  const listener = this.on('event', (...args) => {
    if(filter(...args)) {
      listener.off();
      resolve(...args);
    }
  }, {objectify: true});
});
```

**Comment by DigitalBrainJS** [comment]
@kelvinhammond Thanks for reporting! Fixed. Will be released in 6.4.3 patch.
