### ISSUE TITLE
Objectify is ignored with wildcard = true

### ISSUE THREAD

**Issue by jezaman** [EventEmitter2/EventEmitter2#265]
Setting objectify to true will still return the EventEmitter instance when wildcard is set to true. 
 
Can be fixed by changing  part of the function 
`EventEmitter.prototype._on = function(type, listener, prepend, options) `

`if (this.wildcard) {
      growListenerTree.call(this, type, listener);
      return this;
    }`

to

`if (this.wildcard) {
      growListenerTree.call(this, type, listener);
      return returnValue;
    }`

**Comment by DigitalBrainJS** [comment]
Fixed. Scheduled for 6.4.3 release. Thanks for reporting!
