### ISSUE TITLE
Missing GitHub releases

### ISSUE THREAD

**Issue by intelliot** [EventEmitter2/EventEmitter2#273]
This page: https://github.com/EventEmitter2/EventEmitter2/releases

v6.0.0 is shown as the "Latest release" but 6.4.4 has already been released on npm.

There's a tag for v6.4.3. But no tag for v6.4.4 yet.

**Comment by DigitalBrainJS** [comment]
Just fixed it. It looks like we should add a release script to avoid this in the future...

**Comment by intelliot** [comment]
Thanks
