### ISSUE TITLE
Waiting for event to finish

### ISSUE THREAD

**Issue by kristijanhusak** [EventEmitter2/EventEmitter2#275]
Hi,

is there a way to wait for specific event to finish?

Example:

```javascript
// Listener somewhere in the code base that needs at least 1 sec to finish

emitter.on('test-event', async (userId) => {
  await new Promise((resolve) => setTimeout(resolve('finished'), 1000); // simulate slow db update
  return User.update(id, { done: true });
});
```

```javascript
// Code somewhere in the code base that triggers the event
function markUserDone(id) {
  // some code here
  emitter.emit('test-event', userId)
}

```

```javascript
// Test that ensures event was fired and processed

markUserDone(1);

// here I need to wait at least 1 sec
// example implementation: await emitter.waitForEventToFinish('test-event')

const user = User.find(1)
expect(user.done).toBe(true);
```

**Comment by DigitalBrainJS** [comment]
There is currently no such feature out of the box in EventEmitter2. But you can use a workaround for this with an additional subevent ([Live Demo](https://codesandbox.io/s/epic-ardinghelli-0lyon?file=/src/index.js)):

```javascript
const emitter = new EventEmitter2({
  wildcard: true
});

async function emitAsyncWithNotification(emitter, event, ...args) {
  const results = await emitter.emitAsync(event, ...args);
  emitter.emit([event, "finished"], ...results);
  return results;
}

emitter.on("test-event", async (userId) => {
  await new Promise((resolve) => setTimeout(resolve, 1000)); // simulate slow db update
  log("async handler completed");
  return `Resolved user data for ${userId}`;
});

function markUserDone(userId) {
  emitAsyncWithNotification(emitter, "test-event", userId);
}

markUserDone(1);

log("event fired");

(async () => {
  const results = await emitter.waitFor(["test-event", "finished"]);

  log("waitFor completed", results);
})();
```

**Comment by kristijanhusak** [comment]
Thanks. Are there any plans to introduce this as part of the plugin?

**Comment by DigitalBrainJS** [comment]
Maybe. This is not as easy as it might seem. The above code is just a partial solution for the wildcard emitter. It cannot be injected into the core API as it is, since the internal complete listener is public, so it will affect other methods. I'm not sure if the users of the package want the internal listener to affect `onAny`, `listenersCount`, `hasListeners`, etc. At the very least, we need to do some research to find the best approach without potential breaking changes, adding a lot of code, or performance issues. It seems like a separate data structure for private event listeners would be the best solution at the moment.

**Comment by kristijanhusak** [comment]
I understand. It is indeed a complex thing.

I need this only for testing purposes. Basically, I call an endpoint, that does something, and triggers the event to do something additional. Then I'm trying to wait for that event that was triggered to finish, so I can do assertions.

Workaround is to "sleep" for some amount of time, but that is either unnecessary too long, or not long enough, which makes tests brittle.
Maybe i'm not testing this in a proper way, who knows.

Anyway, thanks for your help.
