### ISSUE TITLE
Graceful Shutdown 

### ISSUE THREAD

**Issue by diegodario88** [EventEmitter2/EventEmitter2#284]
Hi, congrats on the awesome work here 

I wonder if is there any example on how to properly shutdown the application in a way that we await for any events that may be running? 

If not, is there a way to check such information? 

Like:
```
process.on('beforeExit', signal => {

 // look up for events that may be processing something and then await for those
 
});
```

**Comment by RangerMauve** [comment]
Sadly there's no way to know what async events are in progress from within eventemitter. You'll likely want to wrap calls to `emitAsync` in some sort of queue within your application and keep track of it there.
