### ISSUE TITLE
Feature Request: await emitter.onAny()

### ISSUE THREAD

**Issue by vader-sama** [EventEmitter2/EventEmitter2#288]
Hello.
I think it would be nice to have a method like `Promise.race()` for events!
like wait for first event that have been emitted.
In one of my recent projects I really needed this functionality, I had to create a wrapper around the emitter to make it work.
It would be nice if the package supports this feature.
```js
const emitter = new EventEmitter2()
emitter.emit("first", true)

await emitter.onAny() // { event: "first", args: [true] }
```

**Comment by RangerMauve** [comment]
This seems like it might require a major overhaul with performance implications. Might be better to wrap eventemittter2 with a higher order library if you need this functionality. 😁
