### ISSUE TITLE
Mixing in EventEmitter2

### ISSUE THREAD

**Issue by jvduf** [EventEmitter2/EventEmitter2#7]
The native Node.js EventEmitter can be mixed in or used as inheritor for other objects. Using the constructor of EventEmitter2 to initialize and setup some of the basic properties prevents that from being possible (as far as my knowledge goes).

In the examples in the documentation you are using EventEmitter2 as the base object to "create" a new server, this however is not a real server but just an EventEmitter so that's why you probably haven't run into this issue yet :)

Looking into the core API's of Node.js, the native EventEmitter is inherited with a utility function to basically copy it's properties / functions to the other object. For an example see:

https://github.com/joyent/node/blob/master/lib/http.js#L1142

I would like to be able to do this with EventEmitter2 as well. 

Do you agree if I fix EventEmitter2 so it can be used as the native EventEmitter and be mixed in with other objects using the utility function?

**Comment by mcasimir** [comment]
Still not working for me.

``` js
var EventEmitter2 = require('eventemitter2').EventEmitter2;

function Backend(endpoint, http, ws) {
  EventEmitter2.call(this);

  this.endpoint = http;
  this.http = http;
  this.ws = ws;
}

module.exports = Backend;
```

``` js
var Backend = require('../../src/backend');
var backend = new Backend();
console.log(typeof backend.on);
// -> undefined
```

Anyway this is is a quite common use case, definitely consider to document it at least.

**Comment by julianh2o** [comment]
I ran into this too. I was looking to "upgrade" from EventEmitter to EventEmitter2 because of the onAny support but my code uses util.inherits. It's not a problem to refactor my code, but it caught me by surprise as I was expecting a drop-in replacement.
